package com.thinging.project.errors.utils;

public enum ErrorCode {
    STATUS_OK,
    STATUS_CREATED,
    ILLEGAL_ARGUMENT,
    SERVER_NOT_STARTED,
    SERVER_STARTED,
    RESORCE_NOT_EXISTS,
    MQTT_ERROR,
    WRONG_SERVICE_TYPE,
    WRONG_EVENT_TYPE,
    GROUP_EXISTS,
    GROUP_NOT_EXISTS,
    THING_EXISTS,
    THING_NOT_EXISTS,
    JOB_EXISTS,
    JOB_NOT_EXISTS,
    JOB_STATUS_INVALID,
    DUPLICATED_VALUE,
    USER_EXISTS,
    USER_NOT_EXISTS,
    NULL_VALUE,
}
